### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by obuw** [Kapps/PoEWhisperNotifier#23]
The new version seems to be crashing constantly, upon receipt of a message. Not sure if it is possible to provide an error log?

**Comment by LoneWolfHowl** [comment]
I am also getting this. I looked and didn't see a log but can provide one if I know where to look.

I have default settings on Windows 7 64-bit.

**Comment by Kapps** [comment]
Do either of you have Minimize on Startup enabled? It's not enabled by default.

**Comment by obuw** [comment]
I did, yeah. But I did suspect it might have something to do with it (since it's one of the few added things in the new version), so I doubleclicked the tray icon to open the window. Still crashed later on.

(I didn't try disabling the option completely. But I'm now back to 1.9 which works fine.)

**Comment by Kapps** [comment]
Ahh there we go, able to duplicate the issue now. There's no window created yet when minimize on startup is enabled, so the stuff that relies on the window handle for communicating ends up crashing it. I'll put out a fix for that shortly, but the crashing later even if you double-click the tray is odd... that shouldn't be the case here because when you double-click it it does get created.

**Comment by obuw** [comment]
Maybe the variable doesn't get initialized properly on double click or something? Or perhaps I'm confusing my steps. Either way I'll test with the new version once it's out, and let you know if I get any more crashes.

**Comment by Kapps** [comment]
Should hopefully be fixed now in 2.0b (https://github.com/Kapps/PoEWhisperNotifier/releases/tag/v2.0b). If it's not, I added logging on unhandled exceptions, which really should have existed before. :P

**Comment by LoneWolfHowl** [comment]
Sorry I had it enabled also. I will try out the new version. Thank you!!

**Comment by RyuuOujiXS** [comment]
New version still crashes.  It'll even crash while running with the window up.  It'll just freeze and stop responding. Have to end task. We can help you better if you add logging.

**Comment by Kapps** [comment]
This may hopefully actually be fixed in the newest release. If it's not, then I'm honestly pretty stumped. I can't replicate this at all no matter what I do.
