### ISSUE TITLE
Receiving notifications when in game

### ISSUE THREAD

**Issue by Wraeyth** [Kapps/PoEWhisperNotifier#9]
I'm receiving notifications when I'm in game and active as of a few days ago. I even receive them for whispers I send.

**Comment by Kapps** [comment]
Make sure you have Settings -> Notify Only When Minimized checked off.

If you do and you still have the issue, have you restarted your computer in the last month or so? If not, try downloading the latest version of the whisper notifier, it has a fix that could be related to this. Alternatively, you could just reboot and if that's the issue, it will fix it as well. I would be curious to see if my fix worked though (it should).

**Comment by Wraeyth** [comment]
I'll test your fix when I am at my pc next. The setting is checked, always has been. Will update once I've tested.

**Comment by Kapps** [comment]
I shall assume this is fixed. :)

**Comment by Wraeyth** [comment]
Hi yes, sorry. It still occurs but very rarely and not for very long.
Please close.

**Comment by Kapps** [comment]
Hmm. Another possibility is that it was detecting the wrong PoE process. The old approach was pretty lousy and could lead to false positives (like Chrome when your active tab was the PoE forums) since I didn't have access to the Steam version of the game. It's also possible your issue could be fixed in 1.8 since I take an approach that shouldn't lead to false positives anymore.
